language: php

php:
  - "5.6"
  - "5.5"
  - "7.0"
  - "7.1"
  - "hhvm"

before_script:
  - travis_retry composer install --no-interaction
  - cp phpspec.yml.dist phpspec.yml

script:
  - ./vendor/bin/phpspec run --config=phpspec.yml --no-interaction --format=pretty